### PR TITLE
Introduce TravisCI + Small perlcritic changes

### PR DESCRIPTION
**Pull request by lancew**
I am not sure how to break the first two commits from the rest (or squash perhaps), sorry.

First two commits address some minor perlcritic errors.
Remaining ones enable TravisCI testing.

Done as part of CPAN Pull Request Challenge. Feedback appreciated.

### CODE REVIEW

**Comment by shlomif** [comment]
Thanks, Lance! I'll take a look.

**Comment by shlomif** [comment]
Hi Lance!

Some comments on your pull-request:

1. In t/*.t `eval { use MyMod; }` instead of `eval "use MyMod;"` is wrong and will unconditionally try to load the module and throw an exception if it isn't (that's because use is compile-time):

```
shlomif@telaviv1:~/progs/perl/cpan/Math/Math-Cephes$ perl -E 'eval { use NonExist; }'
Can't locate NonExist.pm in @INC (you may need to install the NonExist module)
.
.
.
shlomif@telaviv1:~$ perl -E 'eval { require NonExist; }'
shlomif@telaviv1:~$ 
```

so either put require and/or "require; import" there or keep it as string eval.

2. 

```
-        print MCONF fix_mconf($def, $defs{$def});
+        print $mconf_fh fix_mconf($def, $defs{$def});
```

`print $fh @args` is better written as `print {$fh} @args` (see http://perl-begin.org/tutorials/bad-elements/#print_to_fh ). This is a relatively minor problem.

----

Please fix these problems and let me know when I can review your changes again.

**Comment by lancew** [comment]
Thanks for the feedback.
I have put the evals back as they word and updated the filehandle prints.
Lance

**Comment by shlomif** [comment]
Thanks for your contribution! I merged your changes now.

**Pull request merged**
